-- Copyright (C) 2025  Altera Corporation. All rights reserved.
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and any partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, the Altera Quartus Prime License Agreement,
-- the Altera IP License Agreement, or other applicable license
-- agreement, including, without limitation, that your use is for
-- the sole purpose of programming logic devices manufactured by
-- Altera and sold by Altera or its authorized distributors.  Please
-- refer to the Altera Software License Subscription Agreements 
-- on the Quartus Prime software download page.

-- PROGRAM		"Quartus Prime"
-- VERSION		"Version 25.1std.0 Build 1129 10/21/2025 SC Lite Edition"
-- CREATED		"Sat Oct 10 02:23:20 2026"

LIBRARY ieee;
USE ieee.std_logic_1164.all; 

LIBRARY work;

ENTITY BasicCPU IS 
GENERIC (Zero : INTEGER := 0
		);
	PORT
	(
		MAX10_CLK2_50 :  IN  STD_LOGIC;
		PB :  IN  STD_LOGIC_VECTOR(1 DOWNTO 0);
		SW :  IN  STD_LOGIC_VECTOR(9 DOWNTO 0);
		HEX0 :  OUT  STD_LOGIC_VECTOR(6 DOWNTO 0);
		HEX1 :  OUT  STD_LOGIC_VECTOR(6 DOWNTO 0);
		HEX2 :  OUT  STD_LOGIC_VECTOR(6 DOWNTO 0);
		HEX3 :  OUT  STD_LOGIC_VECTOR(6 DOWNTO 0);
		HEX4 :  OUT  STD_LOGIC_VECTOR(6 DOWNTO 0);
		HEX5 :  OUT  STD_LOGIC_VECTOR(6 DOWNTO 0);
		LED :  OUT  STD_LOGIC_VECTOR(9 DOWNTO 0)
	);
END BasicCPU;

ARCHITECTURE bdf_type OF BasicCPU IS 

ATTRIBUTE black_box : BOOLEAN;
ATTRIBUTE noopt : BOOLEAN;

COMPONENT lpm_constant_16
	PORT(		 result : OUT STD_LOGIC_VECTOR(3 DOWNTO 0));
END COMPONENT;
ATTRIBUTE black_box OF lpm_constant_16: COMPONENT IS true;
ATTRIBUTE noopt OF lpm_constant_16: COMPONENT IS true;

COMPONENT busmux_0
	PORT(sel : IN STD_LOGIC;
		 dataa : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 datab : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 result : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;
ATTRIBUTE black_box OF busmux_0: COMPONENT IS true;
ATTRIBUTE noopt OF busmux_0: COMPONENT IS true;

COMPONENT busmux_1
	PORT(sel : IN STD_LOGIC;
		 dataa : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 datab : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 result : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;
ATTRIBUTE black_box OF busmux_1: COMPONENT IS true;
ATTRIBUTE noopt OF busmux_1: COMPONENT IS true;

COMPONENT busmux_10
	PORT(sel : IN STD_LOGIC;
		 dataa : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 datab : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 result : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;
ATTRIBUTE black_box OF busmux_10: COMPONENT IS true;
ATTRIBUTE noopt OF busmux_10: COMPONENT IS true;

COMPONENT busmux_11
	PORT(sel : IN STD_LOGIC;
		 dataa : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 datab : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 result : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;
ATTRIBUTE black_box OF busmux_11: COMPONENT IS true;
ATTRIBUTE noopt OF busmux_11: COMPONENT IS true;

COMPONENT busmux_12
	PORT(sel : IN STD_LOGIC;
		 dataa : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 datab : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 result : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;
ATTRIBUTE black_box OF busmux_12: COMPONENT IS true;
ATTRIBUTE noopt OF busmux_12: COMPONENT IS true;

COMPONENT busmux_13
	PORT(sel : IN STD_LOGIC;
		 dataa : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
		 datab : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
		 result : OUT STD_LOGIC_VECTOR(2 DOWNTO 0));
END COMPONENT;
ATTRIBUTE black_box OF busmux_13: COMPONENT IS true;
ATTRIBUTE noopt OF busmux_13: COMPONENT IS true;

COMPONENT busmux_14
	PORT(sel : IN STD_LOGIC;
		 dataa : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 datab : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 result : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;
ATTRIBUTE black_box OF busmux_14: COMPONENT IS true;
ATTRIBUTE noopt OF busmux_14: COMPONENT IS true;

COMPONENT busmux_2
	PORT(sel : IN STD_LOGIC;
		 dataa : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 datab : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 result : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;
ATTRIBUTE black_box OF busmux_2: COMPONENT IS true;
ATTRIBUTE noopt OF busmux_2: COMPONENT IS true;

COMPONENT busmux_3
	PORT(sel : IN STD_LOGIC;
		 dataa : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 datab : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 result : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;
ATTRIBUTE black_box OF busmux_3: COMPONENT IS true;
ATTRIBUTE noopt OF busmux_3: COMPONENT IS true;

COMPONENT busmux_4
	PORT(sel : IN STD_LOGIC;
		 dataa : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 datab : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 result : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;
ATTRIBUTE black_box OF busmux_4: COMPONENT IS true;
ATTRIBUTE noopt OF busmux_4: COMPONENT IS true;

COMPONENT busmux_5
	PORT(sel : IN STD_LOGIC;
		 dataa : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 datab : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 result : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;
ATTRIBUTE black_box OF busmux_5: COMPONENT IS true;
ATTRIBUTE noopt OF busmux_5: COMPONENT IS true;

COMPONENT busmux_6
	PORT(sel : IN STD_LOGIC;
		 dataa : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 datab : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 result : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;
ATTRIBUTE black_box OF busmux_6: COMPONENT IS true;
ATTRIBUTE noopt OF busmux_6: COMPONENT IS true;

COMPONENT busmux_7
	PORT(sel : IN STD_LOGIC;
		 dataa : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 datab : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 result : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;
ATTRIBUTE black_box OF busmux_7: COMPONENT IS true;
ATTRIBUTE noopt OF busmux_7: COMPONENT IS true;

COMPONENT busmux_8
	PORT(sel : IN STD_LOGIC;
		 dataa : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 datab : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 result : OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;
ATTRIBUTE black_box OF busmux_8: COMPONENT IS true;
ATTRIBUTE noopt OF busmux_8: COMPONENT IS true;

COMPONENT busmux_9
	PORT(sel : IN STD_LOGIC;
		 dataa : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
		 datab : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
		 result : OUT STD_LOGIC_VECTOR(3 DOWNTO 0));
END COMPONENT;
ATTRIBUTE black_box OF busmux_9: COMPONENT IS true;
ATTRIBUTE noopt OF busmux_9: COMPONENT IS true;

COMPONENT nbitpr
GENERIC (CLKN : INTEGER;
			W : INTEGER
			);
	PORT(clk : IN STD_LOGIC;
		 STL : IN STD_LOGIC;
		 I : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 O : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END COMPONENT;

COMPONENT counttwounit
GENERIC (W : INTEGER
			);
	PORT(OPCODE : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
		 CTE : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT nbitlatch
GENERIC (N : INTEGER
			);
	PORT(EN : IN STD_LOGIC;
		 D : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
		 Q : OUT STD_LOGIC_VECTOR(3 DOWNTO 0)
	);
END COMPONENT;

COMPONENT clock_2hz
	PORT(clk_50mhz : IN STD_LOGIC;
		 reset : IN STD_LOGIC;
		 clk_2hz : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT \16bit2ssd\
	PORT(SW : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 HEX0 : OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
		 HEX1 : OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
		 HEX2 : OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
		 HEX3 : OUT STD_LOGIC_VECTOR(6 DOWNTO 0)
	);
END COMPONENT;

COMPONENT hex_to_7seg
	PORT(hex_in : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
		 seg_out : OUT STD_LOGIC_VECTOR(0 TO 6)
	);
END COMPONENT;

COMPONENT shiftunit
GENERIC (W : INTEGER
			);
	PORT(A : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 amt : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
		 F : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
		 O : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END COMPONENT;

COMPONENT ioctrlunit
GENERIC (W : INTEGER
			);
	PORT(IO : IN STD_LOGIC;
		 F : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
		 SWO : OUT STD_LOGIC;
		 SSEN : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT fwdselunit
	PORT(FWEX : IN STD_LOGIC;
		 FWWB : IN STD_LOGIC;
		 exdr : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
		 na : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
		 nb : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
		 wbdr : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
		 selexa : OUT STD_LOGIC;
		 sela : OUT STD_LOGIC;
		 selexb : OUT STD_LOGIC;
		 selb : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT controlunit
	PORT(clk : IN STD_LOGIC;
		 OPCODE : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
		 Halt : OUT STD_LOGIC;
		 Flush : OUT STD_LOGIC;
		 CE : OUT STD_LOGIC;
		 JMP : OUT STD_LOGIC;
		 JAL : OUT STD_LOGIC;
		 JR : OUT STD_LOGIC;
		 BR : OUT STD_LOGIC;
		 CLRC : OUT STD_LOGIC;
		 RDIN : OUT STD_LOGIC;
		 IO : OUT STD_LOGIC;
		 IMMO : OUT STD_LOGIC;
		 EXO : OUT STD_LOGIC;
		 IMMBO : OUT STD_LOGIC;
		 SHFTO : OUT STD_LOGIC;
		 MEMO : OUT STD_LOGIC;
		 ALU2 : OUT STD_LOGIC;
		 REN : OUT STD_LOGIC;
		 CLRR : OUT STD_LOGIC;
		 MEN : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT programcounter
	PORT(clk : IN STD_LOGIC;
		 JMP : IN STD_LOGIC;
		 JAL : IN STD_LOGIC;
		 JR : IN STD_LOGIC;
		 CE : IN STD_LOGIC;
		 CTE : IN STD_LOGIC;
		 CLR : IN STD_LOGIC;
		 BUS_IN : IN STD_LOGIC_VECTOR(8 DOWNTO 0);
		 FULL : OUT STD_LOGIC;
		 EMPTY : OUT STD_LOGIC;
		 AMT : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
		 CO : OUT STD_LOGIC_VECTOR(8 DOWNTO 0)
	);
END COMPONENT;

COMPONENT alu
GENERIC (W : INTEGER
			);
	PORT(A : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 B : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 F : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
		 O : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END COMPONENT;

COMPONENT alu2
GENERIC (W : INTEGER
			);
	PORT(A : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 B : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 F : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
		 V : OUT STD_LOGIC;
		 N : OUT STD_LOGIC;
		 Z : OUT STD_LOGIC;
		 C : OUT STD_LOGIC;
		 O : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END COMPONENT;

COMPONENT branchunit
	PORT(cond : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
		 flags : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
		 BR : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT rom
GENERIC (AW : INTEGER;
			DW : INTEGER;
			SIZE : INTEGER
			);
	PORT(clk : IN STD_LOGIC;
		 EN : IN STD_LOGIC;
		 ADDR : IN STD_LOGIC_VECTOR(8 DOWNTO 0);
		 Dout : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DoutI : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END COMPONENT;

COMPONENT io
GENERIC (W : INTEGER
			);
	PORT(I : IN STD_LOGIC_VECTOR(5 DOWNTO 0);
		 O : OUT STD_LOGIC_VECTOR(5 DOWNTO 0)
	);
END COMPONENT;

COMPONENT nbit4_1mux
GENERIC (W : INTEGER
			);
	PORT(II : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		 IO : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		 OI : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		 OO : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		 S : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
		 O : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
	);
END COMPONENT;

COMPONENT bit2_1mux
	PORT(S : IN STD_LOGIC;
		 I1 : IN STD_LOGIC;
		 I2 : IN STD_LOGIC;
		 O : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT ram
GENERIC (A_WIDTH : INTEGER;
			D_WIDTH : INTEGER;
			SIZE : INTEGER
			);
	PORT(clk : IN STD_LOGIC;
		 EN : IN STD_LOGIC;
		 WE : IN STD_LOGIC;
		 ADDR_IN : IN STD_LOGIC_VECTOR(8 DOWNTO 0);
		 ADDR_OUT1 : IN STD_LOGIC_VECTOR(8 DOWNTO 0);
		 DIN : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DOUT : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END COMPONENT;

COMPONENT registers
GENERIC (AW : INTEGER;
			W : INTEGER
			);
	PORT(ENI : IN STD_LOGIC;
		 ENO : IN STD_LOGIC;
		 CLR : IN STD_LOGIC;
		 clk : IN STD_LOGIC;
		 A_ADDR : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
		 B_ADDR : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
		 DATA : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 W_ADDR : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
		 AOUT : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 BOUT : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END COMPONENT;

COMPONENT nbitregister
GENERIC (W : INTEGER
			);
	PORT(clk : IN STD_LOGIC;
		 EN : IN STD_LOGIC;
		 CLR : IN STD_LOGIC;
		 Din : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 Dout : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END COMPONENT;

SIGNAL	A :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	AADDR :  STD_LOGIC_VECTOR(2 DOWNTO 0);
SIGNAL	ALU2_OUT :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	ALU_OUT :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	B :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	BR :  STD_LOGIC;
SIGNAL	CE :  STD_LOGIC;
SIGNAL	const_0 :  STD_LOGIC;
SIGNAL	CountClear :  STD_LOGIC;
SIGNAL	CountEnable :  STD_LOGIC;
SIGNAL	CountJump :  STD_LOGIC;
SIGNAL	CountJumpAndLink :  STD_LOGIC;
SIGNAL	CountTwoEnable :  STD_LOGIC;
SIGNAL	DE_A :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	DE_B :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	DEDEV :  STD_LOGIC_VECTOR(1 DOWNTO 0);
SIGNAL	DEV :  STD_LOGIC_VECTOR(3 DOWNTO 0);
SIGNAL	DEVICE :  STD_LOGIC_VECTOR(3 DOWNTO 0);
SIGNAL	EX_OUT :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	FIN :  STD_LOGIC_VECTOR(3 DOWNTO 0);
SIGNAL	flags :  STD_LOGIC_VECTOR(3 DOWNTO 0);
SIGNAL	Flush :  STD_LOGIC;
SIGNAL	ImmDE :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	ImmEX :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	JMP :  STD_LOGIC;
SIGNAL	JumpRegister :  STD_LOGIC;
SIGNAL	LED_ALTERA_SYNTHESIZED :  STD_LOGIC_VECTOR(9 DOWNTO 0);
SIGNAL	MEM :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	notStalled :  STD_LOGIC;
SIGNAL	OPND :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	OPNDEX :  STD_LOGIC_VECTOR(11 DOWNTO 0);
SIGNAL	OPNDWB :  STD_LOGIC_VECTOR(11 DOWNTO 0);
SIGNAL	OUTPUT :  STD_LOGIC_VECTOR(6 DOWNTO 0);
SIGNAL	OUTSEL :  STD_LOGIC_VECTOR(6 DOWNTO 0);
SIGNAL	RA :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	RB :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	RDIN :  STD_LOGIC;
SIGNAL	RegisterClearAll :  STD_LOGIC;
SIGNAL	REN :  STD_LOGIC;
SIGNAL	SHARED_BUS :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SHFT_OUT :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SSD :  STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL	SSDTAP :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	STALL_DEEX :  STD_LOGIC;
SIGNAL	STALL_EXWB :  STD_LOGIC;
SIGNAL	STALL_IF :  STD_LOGIC;
SIGNAL	STALL_IFDE :  STD_LOGIC;
SIGNAL	STAT1 :  STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL	STAT2 :  STD_LOGIC_VECTOR(8 DOWNTO 0);
SIGNAL	STAT3 :  STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL	STAT4 :  STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL	SW10 :  STD_LOGIC;
SIGNAL	SW11 :  STD_LOGIC;
SIGNAL	SW12 :  STD_LOGIC;
SIGNAL	SW13 :  STD_LOGIC;
SIGNAL	SW14 :  STD_LOGIC;
SIGNAL	SW15 :  STD_LOGIC;
SIGNAL	SWO :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_45 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_5 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_6 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_7 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_9 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_10 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_11 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_12 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_13 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_46 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_15 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_16 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_17 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_18 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_19 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_21 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_22 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_23 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_24 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_25 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_26 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_27 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_28 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_29 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_30 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_31 :  STD_LOGIC_VECTOR(3 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_32 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_33 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_35 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_36 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_37 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_38 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_39 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_40 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_41 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_42 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_43 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_44 :  STD_LOGIC;

SIGNAL	GDFX_TEMP_SIGNAL_0 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	GDFX_TEMP_SIGNAL_1 :  STD_LOGIC_VECTOR(1 DOWNTO 0);

BEGIN 
SYNTHESIZED_WIRE_5 <= '0';
SYNTHESIZED_WIRE_21 <= '1';
SYNTHESIZED_WIRE_27 <= '0';
SYNTHESIZED_WIRE_29 <= '0';
SYNTHESIZED_WIRE_35 <= '1';
SYNTHESIZED_WIRE_36 <= '1';
SYNTHESIZED_WIRE_37 <= '0';
SYNTHESIZED_WIRE_44 <= '0';

GDFX_TEMP_SIGNAL_0 <= (SW15 & SW14 & SW13 & SW12 & SW11 & SW10 & SW(9) & SW(8) & SW(7) & SW(6) & SW(5) & SW(4) & SW(3) & SW(2) & SW(1) & SW(0));
GDFX_TEMP_SIGNAL_1 <= (SW11 & SW10);


b2v_ABuffer : nbitpr
GENERIC MAP(CLKN => 1,
			W => 16
			)
PORT MAP(clk => LED_ALTERA_SYNTHESIZED(8),
		 STL => SYNTHESIZED_WIRE_45,
		 I => DE_A,
		 O => A);


b2v_BBuffer : nbitpr
GENERIC MAP(CLKN => 1,
			W => 16
			)
PORT MAP(clk => LED_ALTERA_SYNTHESIZED(8),
		 STL => SYNTHESIZED_WIRE_45,
		 I => DE_B,
		 O => B);


b2v_checkInstructionLength : counttwounit
GENERIC MAP(W => 16
			)
PORT MAP(OPCODE => OPND(15 DOWNTO 12),
		 CTE => SYNTHESIZED_WIRE_9);


DEV(3) <= OUTPUT(4) AND OPNDEX(0) AND OPNDEX(1) AND OPNDEX(2);


b2v_DEVICESELECT : nbitpr
GENERIC MAP(CLKN => 1,
			W => 4
			)
PORT MAP(clk => LED_ALTERA_SYNTHESIZED(8),
		 STL => STALL_EXWB,
		 I => DEV,
		 O => DEVICE);


b2v_DeviceSelRegister : nbitpr
GENERIC MAP(CLKN => 1,
			W => 2
			)
PORT MAP(clk => LED_ALTERA_SYNTHESIZED(8),
		 STL => SYNTHESIZED_WIRE_45,
		 I => DEDEV,
		 O => DEV(1 DOWNTO 0));


b2v_ExecuteOperands : nbitpr
GENERIC MAP(CLKN => 1,
			W => 12
			)
PORT MAP(clk => LED_ALTERA_SYNTHESIZED(8),
		 STL => SYNTHESIZED_WIRE_45,
		 I => OPND(11 DOWNTO 0),
		 O => OPNDEX);


b2v_ExecuteOutput : nbitpr
GENERIC MAP(CLKN => 1,
			W => 16
			)
PORT MAP(clk => LED_ALTERA_SYNTHESIZED(8),
		 STL => STALL_EXWB,
		 I => EX_OUT,
		 O => SHARED_BUS);


b2v_FlagLatches : nbitlatch
GENERIC MAP(N => 4
			)
PORT MAP(EN => DEV(3),
		 D => FIN,
		 Q => flags);


b2v_immBMux : busmux_0
PORT MAP(sel => OUTPUT(6),
		 dataa => B,
		 datab => ImmEX,
		 result => SYNTHESIZED_WIRE_10);


b2v_ImmeRegister : nbitpr
GENERIC MAP(CLKN => 1,
			W => 16
			)
PORT MAP(clk => LED_ALTERA_SYNTHESIZED(8),
		 STL => SYNTHESIZED_WIRE_45,
		 I => ImmDE,
		 O => ImmEX);


b2v_inst : clock_2hz
PORT MAP(clk_50mhz => MAX10_CLK2_50,
		 reset => SYNTHESIZED_WIRE_5,
		 clk_2hz => SYNTHESIZED_WIRE_32);


b2v_inst1 : \16bit2ssd\
PORT MAP(SW => SYNTHESIZED_WIRE_6,
		 HEX0 => HEX0,
		 HEX1 => HEX1,
		 HEX2 => HEX2,
		 HEX3 => HEX3);


SYNTHESIZED_WIRE_33 <= SYNTHESIZED_WIRE_7 OR STALL_IF;



SYNTHESIZED_WIRE_7 <= SYNTHESIZED_WIRE_45 OR STALL_IFDE;


SYNTHESIZED_WIRE_45 <= STALL_EXWB OR STALL_DEEX;


b2v_inst13 : hex_to_7seg
PORT MAP(hex_in => SSD(3 DOWNTO 0),
		 seg_out => HEX4);


b2v_inst14 : shiftunit
GENERIC MAP(W => 16
			)
PORT MAP(A => A,
		 amt => OPNDEX(5 DOWNTO 3),
		 F => OPNDEX(2 DOWNTO 0),
		 O => SHFT_OUT);


b2v_inst15 : hex_to_7seg
PORT MAP(hex_in => SSD(7 DOWNTO 4),
		 seg_out => HEX5);






b2v_inst2 : ioctrlunit
GENERIC MAP(W => 16
			)
PORT MAP(IO => OUTPUT(0),
		 F => OPNDEX(2 DOWNTO 0),
		 SWO => SWO,
		 SSEN => DEV(2));



b2v_inst21 : fwdselunit
PORT MAP(FWEX => DEV(0),
		 FWWB => DEVICE(0),
		 exdr => OPNDEX(11 DOWNTO 9),
		 na => AADDR,
		 nb => OPND(8 DOWNTO 6),
		 wbdr => OPNDWB(11 DOWNTO 9),
		 selexa => SYNTHESIZED_WIRE_40,
		 sela => SYNTHESIZED_WIRE_38,
		 selexb => SYNTHESIZED_WIRE_41,
		 selb => SYNTHESIZED_WIRE_42);



CountTwoEnable <= SYNTHESIZED_WIRE_9 AND CountEnable;


b2v_inst24 : controlunit
PORT MAP(clk => LED_ALTERA_SYNTHESIZED(8),
		 OPCODE => STAT1(7 DOWNTO 4),
		 CE => CE,
		 JMP => JMP,
		 JAL => CountJumpAndLink,
		 JR => JumpRegister,
		 BR => BR,
		 CLRC => CountClear,
		 RDIN => RDIN,
		 IO => OUTSEL(0),
		 IMMO => OUTSEL(2),
		 EXO => OUTSEL(1),
		 IMMBO => OUTSEL(6),
		 SHFTO => OUTSEL(3),
		 MEMO => OUTSEL(5),
		 ALU2 => OUTSEL(4),
		 REN => DEDEV(0),
		 MEN => DEDEV(1));


b2v_inst25 : programcounter
PORT MAP(clk => LED_ALTERA_SYNTHESIZED(8),
		 JMP => CountJump,
		 JAL => CountJumpAndLink,
		 JR => JumpRegister,
		 CE => CountEnable,
		 CTE => CountTwoEnable,
		 CLR => CountClear,
		 BUS_IN => OPND(8 DOWNTO 0),
		 FULL => LED_ALTERA_SYNTHESIZED(0),
		 EMPTY => LED_ALTERA_SYNTHESIZED(1),
		 AMT => STAT1(3 DOWNTO 0),
		 CO => STAT2);


CountEnable <= CE AND notStalled;


SW11 <= NOT(PB(1));



SW10 <= NOT(PB(0));



b2v_inst29 : alu
GENERIC MAP(W => 16
			)
PORT MAP(A => A,
		 B => SYNTHESIZED_WIRE_10,
		 F => OPNDEX(2 DOWNTO 0),
		 O => ALU_OUT);


SYNTHESIZED_WIRE_46 <= OUTPUT(1) OR SWO;


b2v_inst33 : busmux_1
PORT MAP(sel => OUTPUT(5),
		 dataa => SHFT_OUT,
		 datab => MEM,
		 result => SYNTHESIZED_WIRE_18);


b2v_inst34 : busmux_2
PORT MAP(sel => SYNTHESIZED_WIRE_11,
		 dataa => SYNTHESIZED_WIRE_12,
		 datab => SYNTHESIZED_WIRE_13,
		 result => EX_OUT);


b2v_inst35 : busmux_3
PORT MAP(sel => SYNTHESIZED_WIRE_46,
		 dataa => ImmEX,
		 datab => SYNTHESIZED_WIRE_15,
		 result => SYNTHESIZED_WIRE_13);


b2v_inst36 : busmux_4
PORT MAP(sel => SYNTHESIZED_WIRE_16,
		 dataa => SYNTHESIZED_WIRE_17,
		 datab => SYNTHESIZED_WIRE_18,
		 result => SYNTHESIZED_WIRE_12);


b2v_inst37 : busmux_5
PORT MAP(sel => OUTPUT(4),
		 dataa => ALU_OUT,
		 datab => ALU2_OUT,
		 result => SYNTHESIZED_WIRE_17);


b2v_inst38 : busmux_6
PORT MAP(sel => SWO,
		 dataa => A,
		 datab => GDFX_TEMP_SIGNAL_0,
		 result => SYNTHESIZED_WIRE_15);


b2v_inst39 : alu2
GENERIC MAP(W => 16
			)
PORT MAP(A => A,
		 B => B,
		 F => OPNDEX(2 DOWNTO 0),
		 V => FIN(0),
		 N => FIN(1),
		 Z => FIN(2),
		 C => FIN(3),
		 O => ALU2_OUT);



b2v_inst40 : busmux_7
PORT MAP(sel => SW11,
		 dataa => SYNTHESIZED_WIRE_19,
		 datab => SSDTAP,
		 result => SYNTHESIZED_WIRE_6);


SYNTHESIZED_WIRE_11 <= OUTPUT(2) OR SYNTHESIZED_WIRE_46;


b2v_inst42 : busmux_8
PORT MAP(sel => SW10,
		 dataa => EX_OUT,
		 datab => SHARED_BUS,
		 result => SSDTAP);


b2v_inst44 : branchunit
PORT MAP(cond => OPND(11 DOWNTO 9),
		 flags => flags,
		 BR => SYNTHESIZED_WIRE_24);


b2v_inst45 : rom
GENERIC MAP(AW => 9,
			DW => 16,
			SIZE => 512
			)
PORT MAP(clk => LED_ALTERA_SYNTHESIZED(8),
		 EN => SYNTHESIZED_WIRE_21,
		 ADDR => STAT2,
		 Dout => OPND,
		 DoutI => ImmDE);


CountJump <= SYNTHESIZED_WIRE_22 OR JMP;



SYNTHESIZED_WIRE_23 <= NOT(DEVICE(2));



LED_ALTERA_SYNTHESIZED(2) <= NOT(SYNTHESIZED_WIRE_23);



SYNTHESIZED_WIRE_22 <= SYNTHESIZED_WIRE_24 AND BR;


SYNTHESIZED_WIRE_25 <= NOT(SWO);



LED_ALTERA_SYNTHESIZED(3) <= NOT(SYNTHESIZED_WIRE_25);



SYNTHESIZED_WIRE_26 <= NOT(REN);



LED_ALTERA_SYNTHESIZED(4) <= NOT(SYNTHESIZED_WIRE_26);



SYNTHESIZED_WIRE_28 <= NOT(SYNTHESIZED_WIRE_27);



LED_ALTERA_SYNTHESIZED(5) <= NOT(SYNTHESIZED_WIRE_28);



SYNTHESIZED_WIRE_30 <= NOT(SYNTHESIZED_WIRE_29);



LED_ALTERA_SYNTHESIZED(6) <= NOT(SYNTHESIZED_WIRE_30);




SYNTHESIZED_WIRE_16 <= OUTPUT(3) OR OUTPUT(5);


b2v_inst60 : io
GENERIC MAP(W => 6
			)
PORT MAP(I => OUTPUT(5 DOWNTO 0),
		 O => STAT3(5 DOWNTO 0));


b2v_inst62 : busmux_9
PORT MAP(sel => LED_ALTERA_SYNTHESIZED(9),
		 dataa => OPND(15 DOWNTO 12),
		 datab => SYNTHESIZED_WIRE_31,
		 result => STAT1(7 DOWNTO 4));





b2v_inst66 : nbit4_1mux
GENERIC MAP(W => 8
			)
PORT MAP(II => STAT4,
		 IO => STAT3,
		 OI => STAT2(7 DOWNTO 0),
		 OO => STAT1,
		 S => GDFX_TEMP_SIGNAL_1,
		 O => SSD);


b2v_inst67 : io
GENERIC MAP(W => 6
			)
PORT MAP(I => OUTSEL(5 DOWNTO 0),
		 O => STAT4(5 DOWNTO 0));




b2v_inst76 : bit2_1mux
PORT MAP(S => SW(0),
		 I1 => MAX10_CLK2_50,
		 I2 => SYNTHESIZED_WIRE_32,
		 O => LED_ALTERA_SYNTHESIZED(8));


LED_ALTERA_SYNTHESIZED(7) <= CountTwoEnable OR CountEnable;


REN <= DEVICE(3) XOR DEVICE(0);


notStalled <= NOT(SYNTHESIZED_WIRE_33);



b2v_OUTPUTSELECT : nbitpr
GENERIC MAP(CLKN => 1,
			W => 7
			)
PORT MAP(clk => LED_ALTERA_SYNTHESIZED(8),
		 STL => SYNTHESIZED_WIRE_45,
		 I => OUTSEL,
		 O => OUTPUT);


b2v_ProgramMemory : ram
GENERIC MAP(A_WIDTH => 9,
			D_WIDTH => 16,
			SIZE => 128
			)
PORT MAP(clk => LED_ALTERA_SYNTHESIZED(8),
		 EN => SYNTHESIZED_WIRE_35,
		 WE => DEVICE(1),
		 ADDR_IN => OPNDWB(8 DOWNTO 0),
		 ADDR_OUT1 => OPND(8 DOWNTO 0),
		 DIN => SHARED_BUS,
		 DOUT => MEM);


b2v_registerFile : registers
GENERIC MAP(AW => 3,
			W => 16
			)
PORT MAP(ENI => REN,
		 ENO => SYNTHESIZED_WIRE_36,
		 CLR => SYNTHESIZED_WIRE_37,
		 clk => LED_ALTERA_SYNTHESIZED(8),
		 A_ADDR => AADDR,
		 B_ADDR => OPND(5 DOWNTO 3),
		 DATA => SHARED_BUS,
		 W_ADDR => OPNDWB(11 DOWNTO 9),
		 AOUT => RA,
		 BOUT => RB);


b2v_SelA : busmux_10
PORT MAP(sel => SYNTHESIZED_WIRE_38,
		 dataa => RA,
		 datab => SYNTHESIZED_WIRE_39,
		 result => DE_A);


b2v_SelA25 : busmux_11
PORT MAP(sel => SYNTHESIZED_WIRE_40,
		 dataa => SHARED_BUS,
		 datab => EX_OUT,
		 result => SYNTHESIZED_WIRE_39);


b2v_SelA26 : busmux_12
PORT MAP(sel => SYNTHESIZED_WIRE_41,
		 dataa => SHARED_BUS,
		 datab => EX_OUT,
		 result => SYNTHESIZED_WIRE_43);


b2v_SelA9 : busmux_13
PORT MAP(sel => RDIN,
		 dataa => OPND(8 DOWNTO 6),
		 datab => OPND(11 DOWNTO 9),
		 result => AADDR);


b2v_SelB : busmux_14
PORT MAP(sel => SYNTHESIZED_WIRE_42,
		 dataa => RB,
		 datab => SYNTHESIZED_WIRE_43,
		 result => DE_B);


b2v_SevenSegmentRegister : nbitregister
GENERIC MAP(W => 16
			)
PORT MAP(clk => LED_ALTERA_SYNTHESIZED(8),
		 EN => DEVICE(2),
		 CLR => SYNTHESIZED_WIRE_44,
		 Din => SHARED_BUS,
		 Dout => SYNTHESIZED_WIRE_19);


b2v_WritebackOperands : nbitpr
GENERIC MAP(CLKN => 1,
			W => 12
			)
PORT MAP(clk => LED_ALTERA_SYNTHESIZED(8),
		 STL => STALL_EXWB,
		 I => OPNDEX,
		 O => OPNDWB);



b2v_ZERO_CONSTANT8 : lpm_constant_16
PORT MAP(		 result => SYNTHESIZED_WIRE_31);

LED <= LED_ALTERA_SYNTHESIZED;

STALL_DEEX <= '0';
STALL_EXWB <= '0';
STALL_IF <= '0';
STALL_IFDE <= '0';
STAT3(7 DOWNTO 6) <= "00";
STAT4(7 DOWNTO 6) <= "00";
END bdf_type;